# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='itemclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptions', models.TextField(max_length=12450)),
                ('shortcuts', models.CharField(max_length=997)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('catagory', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='userclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('account', models.CharField(max_length=200)),
                ('createdate', models.DateTimeField(verbose_name='date published')),
                ('password', models.CharField(max_length=200)),
                ('login_status', models.BooleanField(default=False)),
            ],
        ),
    ]
