# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountmanage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemclass',
            name='publisher',
            field=models.CharField(default=12, max_length=200),
            preserve_default=False,
        ),
    ]
