# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 13:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountmanage', '0002_itemclass_publisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userclass',
            name='createdate',
        ),
    ]
