# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountmanage', '0003_remove_userclass_createdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemclass',
            name='pub_date',
        ),
    ]
