# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountmanage', '0004_remove_itemclass_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemclass',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
